export const demoSave = {
  name: "The Arsenal Project",
  club: "Arsenal",
  current_season: "30/31",
};

export const demoSeasons = [
  {
    id: "1",
    season_year: "25/26",
    country: "England",
    league: "Premier League",
    league_position: 2,
    cup_results: { "FA Cup": "Winner", "Carabao Cup": "Semi Final" },
    european_competition: "Champions League",
    european_stage: "Round of 16",
    top_scorer_name: "Bukayo Saka",
    top_scorer_goals: 24,
    trophies: ["FA Cup"],
    tactic: "4-3-3",
  },
  {
    id: "2",
    season_year: "26/27",
    country: "England",
    league: "Premier League",
    league_position: 1,
    cup_results: { "FA Cup": "Quarter Final", "Carabao Cup": "Winner" },
    european_competition: "Champions League",
    european_stage: "Semi Final",
    top_scorer_name: "Bukayo Saka",
    top_scorer_goals: 31,
    trophies: ["League Title", "Carabao Cup"],
    tactic: "4-3-3",
  },
  {
    id: "3",
    season_year: "27/28",
    country: "England",
    league: "Premier League",
    league_position: 1,
    cup_results: { "FA Cup": "Winner", "Carabao Cup": "Runner Up" },
    european_competition: "Champions League",
    european_stage: "Winner",
    top_scorer_name: "Leandro Trossard",
    top_scorer_goals: 28,
    trophies: ["League Title", "FA Cup", "Champions League"],
    tactic: "4-2-3-1",
  },
  {
    id: "4",
    season_year: "28/29",
    country: "England",
    league: "Premier League",
    league_position: 3,
    cup_results: { "FA Cup": "Semi Final", "Carabao Cup": "First Round" },
    european_competition: "Champions League",
    european_stage: "Quarter Final",
    top_scorer_name: "Ethan Nwaneri",
    top_scorer_goals: 19,
    trophies: [],
    tactic: "4-2-3-1",
  },
  {
    id: "5",
    season_year: "29/30",
    country: "England",
    league: "Premier League",
    league_position: 1,
    cup_results: { "FA Cup": "Winner", "Carabao Cup": "Winner" },
    european_competition: "Champions League",
    european_stage: "Winner",
    top_scorer_name: "Ethan Nwaneri",
    top_scorer_goals: 38,
    trophies: ["League Title", "FA Cup", "Carabao Cup", "Champions League"],
    tactic: "3-4-3",
  },
];